const fs = require('fs');
const path = require('path');

const PORT = Number(process.env.FM_PORT) || 8888;
const ROOT = path.resolve(process.env.FM_ROOT || '/data');
try { fs.mkdirSync(ROOT, { recursive: true }); } catch(e) {}
const REAL_ROOT = fs.realpathSync(ROOT);

// 可选 Basic Auth，格式 "user:pass"，为空则不启用
const AUTH = process.env.FM_AUTH || '';

// 目录大小缓存文件名（存放于 ROOT 下，列表中隐藏）
const SIZE_CACHE_NAME = '.dirsize-cache.json';

const MIME = {
  // Web
  '.html':'text/html;charset=utf-8',
  '.htm':'text/html;charset=utf-8',
  '.css':'text/css',
  '.js':'application/javascript',
  '.json':'application/json',
  '.xml':'text/xml',
  '.csv':'text/csv;charset=utf-8',
  // Images
  '.png':'image/png',
  '.jpg':'image/jpeg',
  '.jpeg':'image/jpeg',
  '.gif':'image/gif',
  '.svg':'image/svg+xml',
  '.bmp':'image/bmp',
  '.tiff':'image/tiff',
  '.tif':'image/tiff',
  '.ico':'image/x-icon',
  '.webp':'image/webp',
  '.avif':'image/avif',
  // Video
  '.mp4':'video/mp4',
  '.webm':'video/webm',
  '.mkv':'video/x-matroska',
  '.avi':'video/x-msvideo',
  '.mov':'video/quicktime',
  '.wmv':'video/x-ms-wmv',
  '.flv':'video/x-flv',
  '.m4v':'video/mp4',
  '.mts':'video/mp2t',
  '.3gp':'video/3gpp',
  // Audio
  '.mp3':'audio/mpeg',
  '.wav':'audio/wav',
  '.ogg':'audio/ogg',
  '.aac':'audio/aac',
  '.flac':'audio/flac',
  '.m4a':'audio/mp4',
  '.wma':'audio/x-ms-wma',
  '.opus':'audio/opus',
  // Documents
  '.pdf':'application/pdf',
  '.doc':'application/msword',
  '.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls':'application/vnd.ms-excel',
  '.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.ppt':'application/vnd.ms-powerpoint',
  '.pptx':'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  // Archives
  '.zip':'application/zip',
  '.rar':'application/vnd.rar',
  '.7z':'application/x-7z-compressed',
  '.tar':'application/x-tar',
  '.gz':'application/gzip',
  '.tgz':'application/gzip',
  '.bz2':'application/x-bzip2',
  '.xz':'application/x-xz',
  '.zst':'application/zstd',
  // Mobile / Desktop apps
  '.apk':'application/vnd.android.package-archive',
  '.ipa':'application/octet-stream',
  '.dmg':'application/x-apple-diskimage',
  '.pkg':'application/x-newton-compatible-pkg',
  '.deb':'application/x-debian-package',
  '.rpm':'application/x-rpm',
  '.msi':'application/x-msi',
  '.exe':'application/vnd.microsoft.portable-executable',
  '.appx':'application/vnd.ms-appx',
  // Fonts
  '.ttf':'font/ttf',
  '.otf':'font/otf',
  '.woff':'font/woff',
  '.woff2':'font/woff2',
  '.eot':'application/vnd.ms-fontobject',
  // Text / Code
  '.txt':'text/plain;charset=utf-8',
  '.md':'text/plain;charset=utf-8',
  '.mdx':'text/plain',
  '.yaml':'text/plain',
  '.yml':'text/plain',
  '.toml':'text/plain',
  '.ini':'text/plain',
  '.cfg':'text/plain',
  '.conf':'text/plain',
  '.env':'text/plain',
  '.log':'text/plain',
  '.sql':'text/plain',
  '.sh':'text/plain',
  '.bash':'text/plain',
  '.zsh':'text/plain',
  '.bat':'text/plain',
  '.cmd':'text/plain',
  '.ps1':'text/plain',
  '.py':'text/plain',
  '.rb':'text/plain',
  '.php':'text/plain',
  '.java':'text/plain',
  '.kt':'text/plain',
  '.kts':'text/plain',
  '.scala':'text/plain',
  '.groovy':'text/plain',
  '.gradle':'text/plain',
  '.c':'text/plain',
  '.cpp':'text/plain',
  '.cc':'text/plain',
  '.cxx':'text/plain',
  '.h':'text/plain',
  '.hpp':'text/plain',
  '.cs':'text/plain',
  '.go':'text/plain',
  '.rs':'text/plain',
  '.swift':'text/plain',
  '.m':'text/plain',
  '.mm':'text/plain',
  '.r':'text/plain',
  '.lua':'text/plain',
  '.pl':'text/plain',
  '.pm':'text/plain',
  '.dart':'text/plain',
  '.ex':'text/plain',
  '.exs':'text/plain',
  '.erl':'text/plain',
  '.hs':'text/plain',
  '.clj':'text/plain',
  '.lisp':'text/plain',
  '.ts':'text/plain',
  '.tsx':'text/plain',
  '.jsx':'text/plain',
  '.vue':'text/plain',
  '.svelte':'text/plain',
  '.astro':'text/plain',
  '.scss':'text/plain',
  '.sass':'text/plain',
  '.less':'text/plain',
  '.graphql':'text/plain',
  '.gql':'text/plain',
  '.proto':'text/plain',
  '.tf':'text/plain',
  '.dockerfile':'text/plain',
  '.gitignore':'text/plain',
  '.dockerignore':'text/plain',
  '.editorconfig':'text/plain',
  '.makefile':'text/plain',
  '.cmake':'text/plain',
};

module.exports = { PORT, ROOT, REAL_ROOT, AUTH, SIZE_CACHE_NAME, MIME };
